import "bulma/css/bulma.min.css";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Provides the root HTML structure for the application, wrapping all content in an English-language HTML and body element.
 * @param {React.ReactNode} children - The content to be rendered within the layout.
 * @return {JSX.Element} The root layout component.
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
