import "bulma/css/bulma.min.css";
import "./globals.css";
// Remover import ThemeToggle

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        />
        <style>{`
          :root {
            --color-primary: #4F8A8B;
            --color-secondary: #FBD46D;
            --color-accent: #F76B8A;
            --color-bg: #F6F6F6;
            --color-bg-card: #FFFFFF;
            --color-text: #232931;
            --color-text-muted: #6E6E6E;
            --color-border: #E0E0E0;
            --color-success: #70D96A;
            --color-error: #F76B8A;
            --color-info: #4F8A8B;
            --color-warning: #FBD46D;
          }
          [data-theme="dark"] {
            --color-primary: #4F8A8B;
            --color-secondary: #FBD46D;
            --color-accent: #F76B8A;
            --color-bg: #232931;
            --color-bg-card: #393E46;
            --color-text: #F6F6F6;
            --color-text-muted: #BDBDBD;
            --color-border: #393E46;
            --color-success: #70D96A;
            --color-error: #F76B8A;
            --color-info: #4F8A8B;
            --color-warning: #FBD46D;
          }
          html, body {
            background: var(--color-bg) !important;
            color: var(--color-text);
          }
          .navbar.is-light {
            background: linear-gradient(90deg, var(--color-primary) 0%, var(--color-secondary) 40%, var(--color-accent) 80%, var(--color-border) 100%);
          }
          .navbar.is-light .navbar-item, .navbar.is-light .navbar-link {
            color: var(--color-text) !important;
            font-weight: 500;
            transition: color .2s;
          }
          .navbar.is-light .navbar-item.has-text-link.active, .navbar.is-light .navbar-link.has-text-link.active {
            color: #fff !important;
          }
          .navbar.is-light .navbar-item:hover, .navbar.is-light .navbar-link:hover {
            color: var(--color-primary) !important;
          }
          .has-text-link, .navbar-item.has-text-link {
            color: var(--color-primary) !important;
          }
          .button.is-link, .is-link {
            background: var(--color-primary) !important;
            border-color: var(--color-secondary) !important;
            color: #fff !important;
          }
          .button.is-link:hover, .button.is-link:focus {
            background: var(--color-accent) !important;
            color: #222 !important;
            box-shadow: 0 2px 8px rgba(106,217,214,0.13);
          }
          .notification.is-success {
            background: var(--color-success);
            color: var(--color-text);
          }
          .notification.is-danger {
            background: var(--color-error);
            color: #fff;
          }
          .notification.is-info {
            background: var(--color-info);
            color: var(--color-primary);
          }
          .notification.is-warning {
            background: var(--color-warning);
            color: var(--color-text);
          }
          .box, .tweet-card {
            border: 1.5px solid var(--color-border);
            background: var(--color-bg-card);
            color: var(--color-text);
          }
        `}</style>
        <script dangerouslySetInnerHTML={{__html:`
          window.toggleTheme = function() {
            const html = document.documentElement;
            const theme = html.getAttribute('data-theme') === 'dark' ? '' : 'dark';
            html.setAttribute('data-theme', theme);
            localStorage.setItem('theme', theme);
          };
          (function(){
            const theme = localStorage.getItem('theme');
            if(theme) document.documentElement.setAttribute('data-theme', theme);
          })();
        `}} />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
